name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # We use the ${{ secrets.HF_TOKEN }} syntax directly in the URL to ensure bash reads it correctly
          git push -f https://z-x-25:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/z-x-25/X main
