name: Sync to Hugging Face Hub
on:
  push:
    branches: [main] # Change to 'master' if your branch is named that
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # We use force push to ensure HF always matches your GitHub exactly
          git push -f https://NodeX-AR:$HF_TOKEN@huggingface.co/spaces/Aswanth/z-x-25-x main
