name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. We use the 'force' flag (-f) so your GitHub always overwrites the Space.
          # 2. Make sure you've added the HF_TOKEN to your GitHub Repo Secrets!
          # 3. Swap 'Aswanth' if your Hugging Face username is different.
          git push -f https://Aswanth:$HF_TOKEN@huggingface.co/spaces/z-x-25/x main
